### PR TITLE
Create container PHP-7 for Centos-7

### PR DESCRIPTION
**Pull request by guiyomh**
Hi,

This PR is a refactoring of the #49 . I removed Oracle Client .
And i added opcache.

### CODE REVIEW

**Comment by guiyomh** [comment]
@mblaschke :+1:

**Comment by toancong** [comment]
Somebody take a look at this PR? Thanks. For centos 7 with php7

**Comment by mblaschke** [comment]
I will do it

**Comment by mblaschke** [comment]
Branch `feature/centos-7-php7` was created from @guiyomh, to check if this code is still working.

**Comment by mblaschke** [comment]
Merged

**Pull request closed without merging**
