### PR TITLE
Chris b9 feature/reenable composer v1

### PR DESCRIPTION
**Pull request by hhoechtl**

### CODE REVIEW

**Comment by wollanup** [comment]
Hi,
Since this change, I have to 
```
RUN composer2 --version
```

instead of a standard

```
RUN composer --version
```
=> `/bin/sh: 1: composer: not found`

Does it sounds acceptable for you ? Shouldn't we use composer 2.x by default with `composer` command and provide a compatibility layer with `composer1` command ?
Or maybe I missed something :)

**Comment by hhoechtl** [comment]
composer 2.x is the default but the symlink is generated during the start of the container (entrypoint).

Therefore if you use the images as a base for building your own, please use `RUN composer1` or `RUN composer2`.
Or if you want to enforce a version, you can do `RUN cp /usr/local/bin/composer2 /usr/local/bin/composer && composer install`

**Comment by ChrisB9** [comment]
@calebfavor The issue with your suggestion is, that the ENV is only accessible on start and not on build.

I think, there needs to be a default composer version, aka composer 2.0 as `composer` and then the entrypoint replaces (maybe overrides with an alias?) the composer version, if the ENV === 1.

**Comment by wollanup** [comment]
@hhoechtl no big deal for me to cp or simlink composer2 to composer, but I think this gonna break a lot of CI and builds out there...
Agree to have a default composer working command, 2.x should work for many of us.
Getting an error with a `composer install` on build was a really strange experience this morning  🤔

**Comment by hhoechtl** [comment]
Fixed with https://github.com/webdevops/Dockerfile/commit/40305a2a77c845356cca3ab005cf2ea5abffe927

**Comment by calebfavor** [comment]
I was able to upgrade to composer v2 and everything is working great after that commit. Thanks so much @hhoechtl

**Pull request merged**
