### PR TITLE
WIP: add php 7.4 release candidate

### PR DESCRIPTION
**Pull request by ChrisB9**
The release-candidate versions of php 7.4 are already out and since a couple days xdebug has added 7.4 beta support.
To be able to test projects and libs prior to 7.4 release, we needed the support of it
7.4 is currently only released for Debian:Buster (10) which is why i added that as well.

This currently is Work in Progress
- [x] provisioning still takes away the conf folder from the 7.4 directory
- [x] docker-php-ext-configure imap --with-kerberos --with-imap-ssl errors with OpenSSL libs not found
- [x] the build process never fully finished, as there is a lot of dependencies that require checking and that take a lot of time
- [ ] mysql-client in debian-buster has been replaced with mariadb-client
- [x] blackfire-io does not yet work in php7.4

+ If anyone wants to support this effort, i welcome any help

### CODE REVIEW

**Comment by hhoechtl** [comment]
Debian 10 would have not been necessary to add (but thanks anyway), because Debian 10 ships with PHP 7.3 by default.
If we add PHP7.4RC it will be based on the official images, so Buster wouldn't not necessary in our image realm.

**Comment by hhoechtl** [comment]
Hmm, the php ext imap bust be kidding:
```
configure: WARNING: unrecognized options: --with-openssl-dir
configure: error: OpenSSL libraries not found.

      Check the path given to --with-openssl-dir and output in config.log)
```

**Comment by hhoechtl** [comment]
@ChrisB9 The conf directory got deleted because `docker/php/7.4` was supposed to be a symlink.
I've deactivated the extensions `imap` and `hash` for now, because they are broken in the current RC.

You can try it in the branch https://github.com/webdevops/Dockerfile/tree/php74

**Comment by ChrisB9** [comment]
I added Debian 10 because i though that this might solve the php-imap issue as php7.4 only has buster images but no stretch anymore, but nope it didnt

- Thanks for solving the broken extension bug and the symlink error :+1: 
 I think, we need to disable blackfire temporarily too... Sadly they do not yet have any support for php7.4, not even here https://github.com/blackfireio/php-sdk

**Comment by ChrisB9** [comment]
It finally did run through for all 7.4 images. I wrapped only the blackfire installation in a php-7.4 condition and not the configuration files etc. as (i hope) we can remove that condition in december anyway

**Comment by hhoechtl** [comment]
I've merged the branch so we can see if the build works. You can view the build history at https://gitlab.com/webdevops/autobuild/pipelines

**Pull request merged**
