### PR TITLE
:sparkles: :books: Add xdebug and blackfire environment variables

### LINKED ISSUE #90: Add XDEBUG env vars
- `XDEBUG_CONNECT_BACK`
- `XDEBUG_REMOTE_HOST`

### LINKED ISSUE #113: Add Blackfire env vars
Blackfire needs an id and token to be written to its .ini file. It looks quite similar to #90 . Would be nice to implement both of these in the same manner. Any idea how #90 will be built? Read an env var and have an entrypoint.d script write it to the .ini?

### PR DESCRIPTION
**Pull request by mblaschke**
Add following environment variables
- XDEBUG_REMOTE_CONNECT_BACK
- XDEBUG_REMOTE_AUTOSTART
- XDEBUG_REMOTE_HOST
- XDEBUG_REMOTE_PORT
- BLACKFIRE_SERVER_ID
- BLACKFIRE_SERVER_TOKEN
Fixes #113
Fixes #90

### CODE REVIEW

**Comment by choonge** [comment]
Awesome! :sparkles:

**Comment by mblaschke** [comment]
Also added blackfire-agent service

**Comment by simonschaufi** [comment]
Shouldn't there be an equal sign also?
Like:
```
xdebug.bla=on
```

**Comment by mblaschke** [comment]
Did i missed something? There are equal signs :)
See https://github.com/webdevops/Dockerfile/pull/115/commits/96f262e8d7f9fcb7b379e3c5e18c1ebc913a3ac0#diff-50a30bfdc5ee820cf1275f7cc3c4bf24R67

**Comment by simonschaufi** [comment]
ah ok, the lines below are just parameters.

**Pull request merged**
