### PR TITLE
Create PHP AUDIT Container

### PR DESCRIPTION
**Pull request by guiyomh**
For the issue #25 

i work on a container that extend webdevops/php and add many tools to audit php code :

- phploc
- pdepend
- phpunit
- phpmd
- phpcs
- phpcbf
- phpcpd
- phpdcd
- phpmetrics
- php-cs-fixer
- deprecation-detector (for symfony)
- php7cc

### CODE REVIEW

**Comment by guiyomh** [comment]
I Will rename the image to php-dev.

**Comment by guiyomh** [comment]
i think, i'll add :
- behat
- xhprof

**Comment by mblaschke** [comment]
Should we add xhprof to php container and xdebug to php-dev?

**Comment by guiyomh** [comment]
show #66

**Pull request closed without merging**
