### PR TITLE
Image make stopped with error

### PR DESCRIPTION
**Pull request by adampweb**
```
~/docker_images/webdevops/Dockerfile $ make all
Traceback (most recent call last):
  File "bin/buildDockerfile.py", line 3, in <module>
    from jinja2 import Environment, FileSystemLoader
ImportError: No module named jinja2
make: *** [provision] Error 1
```

### CODE REVIEW

**Comment by mblaschke** [comment]
Why a pull request?

You have to install pyton jinja2  --> `pip install jinja2`

**Comment by mblaschke** [comment]
BTW: you don't need to build the dockerfiles yourself.. you can fetch the built images from  https://hub.docker.com/u/webdevops/

**Comment by guiyomh** [comment]
@mblaschke : we can close this PR ?

**Comment by mblaschke** [comment]
I've removed the provision part from `make all` so it's working now without jinja2 --> close

**Pull request closed without merging**
