### PR TITLE
Add PHP 8.1 to the docs

### PR DESCRIPTION
**Pull request by pepijnolivier**
It has been available for a while but never added to the docs

https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx.html#docker-image-tags

### CODE REVIEW

**Comment by hhoechtl** [comment]
Thank you for your contribution

**Comment by DataMinded** [comment]
Sorry to be the party crasher , but Prisma cloud says it has some issues open. (1 Critical, 11 High, 13 Medium & 300 Low)

[1](https://imgur.com/a/88pFII4)
[2](https://imgur.com/a/gvD3erf)
[3](https://imgur.com/a/pq29Aou)

Any Ideas on how to fix that ?

**Comment by hhoechtl** [comment]
Actually I don't have an idea. We just use the official PHP images like `php:8.1-fpm-buster` to build our images. 
We even do a full `apt-get upgrade` during build time.

**Comment by DataMinded** [comment]
well for the alpine version it seems like vim is the only one causing problems,  Why is vim in there anyway cant we just get rid of it

**Pull request merged**
